name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set branch to deploy from
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Update index file
        run: |
          cd simple-applet-generator/publicApplets
          node update-index.js
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'simple-applet-generator/publicApplets'  # Upload the publicApplets directory
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
